"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import type { LucideIcon } from "lucide-react";
import {
  ArrowUpRight,
  BarChart3,
  Bell,
  ChevronDown,
  ClipboardCheck,
  CreditCard,
  FolderKanban,
  Home,
  Settings,
  ShieldCheck,
  Sun,
} from "lucide-react";
import { openProductGuide } from "@/components/guide/ProductGuideModal";
import { ContextualBackNav } from "@/components/ui/ContextualBackNav";
import { IconTile } from "@/components/ui/IconTile";
import { OperationalWalletStatus } from "@/components/ui/OperationalWalletStatus";
import { defaultDemoUser, getZilaUserProfile, subscribeToZilaSession, type ZilaUserProfile } from "@/lib/demoSession";
import {
  getLatestPaymentTransaction,
  subscribeToLatestPaymentTransaction,
  type LatestPaymentTransaction,
} from "@/lib/paymentTransactionStore";
import { getStoredProofTransactions, subscribeToProofTransactions } from "@/lib/proofTransactionStore";

interface DesktopShellProps {
  children: ReactNode;
}

interface DesktopNavItem {
  label: string;
  href: string;
  icon: LucideIcon;
  description: string;
}

const desktopNavItems: DesktopNavItem[] = [
  {
    label: "Home",
    href: "/home",
    icon: Home,
    description: "Operational overview",
  },
  {
    label: "Projects",
    href: "/projects",
    icon: FolderKanban,
    description: "Work in motion",
  },
  {
    label: "Payments",
    href: "/payments",
    icon: CreditCard,
    description: "Cross-border payouts",
  },
  {
    label: "Commitments",
    href: "/move-funds",
    icon: ClipboardCheck,
    description: "Approvals and obligations",
  },
  {
    label: "Proof",
    href: "/proof",
    icon: ShieldCheck,
    description: "Verified movement",
  },
  {
    label: "AI Memory",
    href: "/ask",
    icon: BarChart3,
    description: "Operating context",
  },
  {
    label: "Settings",
    href: "/settings",
    icon: Settings,
    description: "Workspace setup",
  },
];

const homeNavItems: DesktopNavItem[] = [
  {
    label: "Home",
    href: "/home",
    icon: Home,
    description: "Operational overview",
  },
  {
    label: "Projects",
    href: "/projects",
    icon: FolderKanban,
    description: "Work in motion",
  },
  {
    label: "Payments",
    href: "/payments",
    icon: CreditCard,
    description: "Cross-border payouts",
  },
  {
    label: "Commitments",
    href: "/move-funds",
    icon: ClipboardCheck,
    description: "Approvals and obligations",
  },
  {
    label: "Proof",
    href: "/proof",
    icon: ShieldCheck,
    description: "Verified movement",
  },
  {
    label: "AI Memory",
    href: "/ask",
    icon: BarChart3,
    description: "Operating context",
  },
  {
    label: "Settings",
    href: "/settings",
    icon: Settings,
    description: "Workspace setup",
  },
];

const pageMeta: Record<string, { title: string; eyebrow: string; summary: string }> = {
  "/home": {
    title: "Operational state",
    eyebrow: "Home",
    summary: "See pressure, payouts, reserves, and verified activity in one operating view.",
  },
  "/projects": {
    title: "Projects",
    eyebrow: "Portfolio",
    summary: "See where supplier timing, reserves, and runway are creating operational pressure.",
  },
  "/ask": {
    title: "Operational update",
    eyebrow: "Context",
    summary: "Tell Zila what changed so projects, payments, reserves, and proof stay aligned.",
  },
  "/payments": {
    title: "Payments",
    eyebrow: "Money coordination",
    summary: "Coordinate supplier payouts, reserves, and money movement across connected rails.",
  },
  "/proof": {
    title: "Proof of Operations",
    eyebrow: "Verified history",
    summary: "Review the verified activity record generated by projects and payments.",
  },
  "/me": {
    title: "Preferences",
    eyebrow: "Profile",
    summary: "Manage your account context, currency defaults, and personal settings.",
  },
  "/settings": {
    title: "Settings",
    eyebrow: "Workspace",
    summary: "Manage your workspace, wallet, payment preferences, and operational setup.",
  },
  "/compare": {
    title: "Operating patterns",
    eyebrow: "Signals",
    summary: "Review recurring behaviour and historical operating patterns.",
  },
};

function getPageMeta(pathname: string) {
  const exact = pageMeta[pathname];
  if (exact) {
    return exact;
  }

  if (pathname.startsWith("/projects/")) {
    return {
      title: "Project operations",
      eyebrow: "Project",
      summary: "Review pressure, commitments, reserves, and the payments needed to keep work moving.",
    };
  }

  if (pathname.startsWith("/payments/")) {
    return {
      title: "Payment coordination",
      eyebrow: "Money movement",
      summary: "Prepare the payout, protect reserves, and attach proof as money moves.",
    };
  }

  return {
    title: "Zila",
    eyebrow: "Workspace",
    summary: "Run the business with one connected operating layer.",
  };
}

function getPrimaryFlowAction(pathname: string) {
  if (pathname === "/projects" || pathname.startsWith("/projects/")) {
    return {
      href: "/payments",
      label: "Make Payment",
      description: "Project pressure becomes payout action",
    };
  }

  if (pathname === "/payments" || pathname.startsWith("/payments/")) {
    return {
      href: "/proof",
      label: "View Generated Proof",
      description: "Payment activity becomes verified memory",
    };
  }

  if (pathname === "/proof") {
    return {
      href: "/payments",
      label: "Back to Payments",
      description: "Proof follows operational movement",
    };
  }

  if (pathname === "/ask") {
    return {
      href: "/projects",
      label: "Review Projects",
      description: "Updates change project pressure",
    };
  }

  if (pathname === "/settings") {
    return {
      href: "/home",
      label: "Back to Dashboard",
      description: "Return to operational state",
    };
  }

  return {
    href: "/payments",
    label: "Make Payment",
    description: "Keep obligations moving",
  };
}

function buildSyncState(latestPayment: LatestPaymentTransaction | null, proofCount: number) {
  if (latestPayment) {
    return {
      label: "Synced just now",
      headline: `${latestPayment.amountLabel} payout synced`,
      detail: "Reserve, proof, and project memory updated",
    };
  }

  if (proofCount > 0) {
    return {
      label: "Proof live",
      headline: `${proofCount} verified records synced`,
      detail: "Operational memory is current",
    };
  }

  return {
    label: "System live",
    headline: "Operations coordinated",
    detail: "Projects, payments, and proof stay aligned",
  };
}

export function DesktopShell({ children }: DesktopShellProps) {
  const pathname = usePathname();
  const meta = getPageMeta(pathname);
  const primaryFlowAction = getPrimaryFlowAction(pathname);
  const isHome = pathname === "/home";
  const visibleNavItems = isHome ? homeNavItems : desktopNavItems;
  const [latestPayment, setLatestPayment] = useState<LatestPaymentTransaction | null>(null);
  const [proofCount, setProofCount] = useState(0);
  const [userProfile, setUserProfile] = useState<ZilaUserProfile>(defaultDemoUser);
  const syncState = useMemo(() => buildSyncState(latestPayment, proofCount), [latestPayment, proofCount]);

  useEffect(() => {
    const updatePayment = () => setLatestPayment(getLatestPaymentTransaction());
    const updateProof = () => setProofCount(getStoredProofTransactions().length);
    const updateSession = () => setUserProfile(getZilaUserProfile());

    updatePayment();
    updateProof();
    updateSession();
    const unsubscribePayment = subscribeToLatestPaymentTransaction(updatePayment);
    const unsubscribeProof = subscribeToProofTransactions(updateProof);
    const unsubscribeSession = subscribeToZilaSession(updateSession);

    return () => {
      unsubscribePayment();
      unsubscribeProof();
      unsubscribeSession();
    };
  }, []);

  return (
    <div
      className={`zila-page-grain hidden min-h-screen w-full lg:block ${
        isHome
          ? "bg-[radial-gradient(ellipse_at_18%_0%,rgba(255,255,255,0.72),transparent_32%),radial-gradient(ellipse_at_86%_7%,rgba(103,232,249,0.24),transparent_28%),radial-gradient(ellipse_at_54%_88%,rgba(109,94,248,0.10),transparent_36%),linear-gradient(180deg,#DCEEFF_0%,#C6DDF8_48%,#AFCBEF_100%)]"
          : "bg-[radial-gradient(ellipse_at_top_left,rgba(255,255,255,0.48),transparent_28%),radial-gradient(ellipse_at_top_right,rgba(103,232,249,0.20),transparent_26%),linear-gradient(180deg,#DCEEFF_0%,#C8DDF6_54%,#B7D0F0_100%)]"
      }`}
    >
      <div className="mx-auto grid min-h-screen w-full max-w-[1228px] grid-cols-[190px_minmax(0,1fr)] gap-3 px-3 py-3 lg:grid-cols-[190px_minmax(0,1fr)] lg:px-4">
        <aside
          className={`zila-sidebar-scroll sticky top-3 flex h-[calc(100vh-1.5rem)] min-h-0 flex-col overflow-y-auto overscroll-contain rounded-[20px] border px-3 py-3 backdrop-blur-xl ${
            isHome
              ? "border-white/28 bg-[radial-gradient(circle_at_16%_0%,rgba(235,243,252,0.16),transparent_30%),radial-gradient(circle_at_108%_18%,rgba(123,178,225,0.13),transparent_34%),radial-gradient(circle_at_28%_78%,rgba(58,104,146,0.16),transparent_38%),linear-gradient(180deg,rgba(67,99,132,0.66),rgba(49,83,121,0.58)_54%,rgba(35,68,105,0.66))] shadow-[0_24px_58px_rgba(31,68,116,0.20),0_0_30px_rgba(123,178,225,0.06),inset_0_1px_0_rgba(246,245,241,0.20),inset_0_-1px_0_rgba(18,44,76,0.12)]"
              : "border-white/24 bg-[radial-gradient(circle_at_18%_0%,rgba(235,243,252,0.14),transparent_30%),radial-gradient(circle_at_106%_18%,rgba(123,178,225,0.12),transparent_32%),radial-gradient(circle_at_30%_80%,rgba(58,104,146,0.14),transparent_38%),linear-gradient(180deg,rgba(64,96,130,0.64),rgba(45,80,118,0.58)_58%,rgba(32,66,103,0.66))] shadow-[0_26px_64px_rgba(31,68,116,0.18),inset_0_1px_0_rgba(246,245,241,0.18),inset_0_-1px_0_rgba(18,44,76,0.12)]"
          }`}
        >
          {isHome ? (
            <>
              <div className="pointer-events-none absolute left-[-34%] top-[-14%] h-48 w-60 rounded-full bg-[radial-gradient(circle_at_50%_50%,rgba(246,245,241,0.14),rgba(246,245,241,0)_72%)] blur-3xl" />
              <div className="pointer-events-none absolute bottom-[-18%] right-[-38%] h-60 w-72 rounded-full bg-[radial-gradient(circle_at_50%_50%,rgba(123,178,225,0.12),rgba(123,178,225,0)_72%)] blur-3xl" />
            </>
          ) : null}
          {isHome ? (
            <div className="relative">
              <div className="sidebar-header">
                <Link href="/home" aria-label="Go to Home" className="sidebar-logo-wrapper cursor-pointer transition duration-200 hover:opacity-85">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src="/logo-full.png" alt="Zila" className="sidebar-logo" />
                </Link>
              </div>

              <div className="profile-section flex items-center gap-3 px-2">
                <div className="relative flex h-12 w-12 items-center justify-center overflow-hidden rounded-full border border-[#EAF1FF]/32 bg-[#14345F] text-[17px] font-semibold text-white shadow-[0_18px_34px_rgba(7,25,50,0.32),inset_0_1px_0_rgba(255,255,255,0.16)]">
                  {userProfile.isDemo ? (
                    <Image
                      src="/zila-profile-kevin.png"
                      alt={userProfile.fullName}
                      fill
                      unoptimized
                      sizes="52px"
                      className="object-cover object-center"
                    />
                  ) : (
                    userProfile.name.charAt(0).toUpperCase()
                  )}
                </div>
                <div className="min-w-0 flex-1">
                  <p className="truncate text-[14px] font-semibold text-[#F7F8FC]">{userProfile.fullName}</p>
                  <p className="mt-0.5 truncate text-[12px] font-medium text-[#D4E0F1]">{userProfile.role}</p>
                </div>
                <ChevronDown className="h-[15px] w-[15px] text-[#D4E0F1]" strokeWidth={2} />
              </div>
            </div>
          ) : (
            <div>
              <div className="sidebar-header">
                <Link href="/home" aria-label="Go to Home" className="sidebar-logo-wrapper cursor-pointer transition duration-200 hover:opacity-85">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src="/logo-full.png" alt="Zila" className="sidebar-logo" />
                </Link>
              </div>
              <div className="px-2">
                <h1 className="mt-2 text-[24px] font-semibold leading-[1.05] tracking-[-0.05em] text-[#F7F8FC]">
                  Projects create pressure. Payments keep work moving.
                </h1>
                <p className="mt-2 text-[12px] leading-[1.55] text-[#A7B0C5]">
                  Proof attaches automatically from the operational activity underneath.
                </p>
              </div>
            </div>
          )}

          <nav className={isHome ? "relative z-10 mt-3 space-y-0.5" : "relative z-10 mt-3 space-y-0.5"}>
            {visibleNavItems.map((item) => {
              const Icon = item.icon;
              const isActive = pathname === item.href || pathname.startsWith(`${item.href}/`);

              return (
                <Link
                  key={item.href}
                  href={item.href}
                  className={`zila-sidebar-nav-link relative z-10 flex cursor-pointer items-center gap-2.5 rounded-[13px] px-2.5 py-1 transition-all duration-200 ${
                    isHome
                      ? isActive
                        ? "border border-[#DCEBFF]/28 bg-[linear-gradient(135deg,rgba(234,241,255,0.17),rgba(126,164,210,0.10))] text-white shadow-[0_15px_32px_rgba(7,25,50,0.24),inset_0_1px_0_rgba(246,245,241,0.18),inset_0_-1px_0_rgba(6,22,42,0.12)]"
                        : "border border-transparent text-[#E0E9F7] hover:border-[#DCEBFF]/18 hover:bg-white/[0.075] hover:shadow-[0_12px_26px_rgba(7,25,50,0.18)]"
                      : isActive
                        ? "border border-[#DCEBFF]/22 bg-[linear-gradient(135deg,rgba(234,241,255,0.14),rgba(102,145,195,0.09))] shadow-[0_16px_34px_rgba(0,0,0,0.22),inset_0_1px_0_rgba(247,248,252,0.14)]"
                        : "border border-transparent text-[#B6C3D6] hover:border-[#DCEBFF]/14 hover:bg-white/[0.07] hover:shadow-[0_12px_26px_rgba(1,8,20,0.18)]"
                  }`}
                >
                  <IconTile
                    glow="none"
                    className={
                      isHome
                        ? `zila-sidebar-nav-icon h-[30px] w-[30px] rounded-[11px] ${isActive ? "zila-sidebar-nav-icon-active" : ""}`
                        : isActive
                          ? "zila-sidebar-nav-icon zila-sidebar-nav-icon-active rounded-[11px]"
                          : "zila-sidebar-nav-icon rounded-[11px]"
                    }
                  >
                    <Icon className={isHome ? "h-[15px] w-[15px]" : "h-[15px] w-[15px]"} strokeWidth={isHome ? 1.9 : 2} />
                  </IconTile>
                  <div className="min-w-0">
                    <p
                      className={`text-[13px] font-semibold ${
                        isHome ? (isActive ? "text-white" : "text-[#F4F8FF]") : isActive ? "text-[#F7F8FC]" : "text-[#EEF4FF]"
                      }`}
                    >
                      {item.label}
                    </p>
                    <p className={`truncate text-[11px] ${isHome ? (isActive ? "text-[#DDE7F6]" : "text-[#D1DCEC]") : "text-[#D4E0F1]"}`}>
                      {item.description}
                    </p>
                  </div>
                  {isActive ? (
                    <span className="ml-auto h-1.5 w-1.5 shrink-0 rounded-full bg-[#A9D8FF] shadow-[0_0_10px_rgba(129,190,245,0.30)]" />
                  ) : null}
                </Link>
              );
            })}
          </nav>

          <div
            className={`zila-card-hover mt-3 rounded-[19px] border p-2.5 text-white ${
              isHome
                ? "border-[#CFE0F6]/22 bg-[radial-gradient(circle_at_100%_0%,rgba(58,122,187,0.24),transparent_38%),linear-gradient(155deg,#173760,#102B50_54%,#0B2141)] shadow-[0_22px_50px_rgba(7,25,50,0.30),inset_0_1px_0_rgba(234,241,255,0.16)]"
                : "border-[#CFE0F6]/16 bg-[linear-gradient(180deg,rgba(19,38,74,0.98),rgba(14,33,63,0.94))] shadow-[0_18px_42px_rgba(1,8,20,0.30)]"
            }`}
          >
            <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#87E6F5]">
              Quick path
            </p>
            <p className="mt-1.5 text-[14px] font-semibold tracking-[-0.03em]">
              Coordinate the next move.
            </p>
            <p className="mt-1.5 text-[11px] leading-[1.5] text-[#E1EAF7]">
              Project pressure, payment timing, and proof stay connected.
            </p>
            <div className="mt-2 rounded-[14px] border border-[#D9FF57]/12 bg-[#D9FF57]/[0.055] px-3 py-2">
              <p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-[#EAFFB4]">
                <span className="zila-live-dot h-1.5 w-1.5 rounded-full bg-[#D9FF57]" />
                {syncState.label}
              </p>
              <p className="mt-1 text-[11px] leading-[1.4] text-[#E3EBFF]">{syncState.detail}</p>
            </div>
            <button
              type="button"
              onClick={openProductGuide}
              className="mt-2.5 inline-flex h-8 w-full items-center justify-center rounded-full border border-[#7CF3FF]/18 bg-white/[0.07] px-4 text-[12px] font-semibold text-white transition hover:bg-white/[0.10]"
            >
              How Zila works
            </button>
            <Link
              href="/payments/send"
              className="zila-button-hover mt-2 inline-flex h-9 w-full items-center justify-center gap-2 rounded-full bg-[#1D4ED8] px-4 text-[13px] font-semibold leading-tight text-white shadow-[0_18px_34px_rgba(29,78,216,0.22)]"
            >
              Make Payment
              <ArrowUpRight className="h-3.5 w-3.5" strokeWidth={2} />
            </Link>
          </div>
        </aside>

        <div className="min-w-0">
          <header
            className={
              isHome
                ? "px-1 py-1"
                : "rounded-[22px] border border-white/10 bg-[linear-gradient(180deg,rgba(22,43,82,0.82),rgba(19,35,71,0.72))] px-4 py-3.5 shadow-[0_22px_52px_rgba(1,8,20,0.22),inset_0_1px_0_rgba(247,248,252,0.08)] backdrop-blur-xl"
            }
          >
            {isHome ? (
              <div className="rounded-[22px] border border-white/22 bg-[linear-gradient(180deg,rgba(64,95,128,0.56),rgba(49,83,121,0.44))] px-4 py-2.5 shadow-[0_16px_34px_rgba(31,68,116,0.18),inset_0_1px_0_rgba(255,255,255,0.18)] backdrop-blur-lg">
                <div className="flex items-center justify-between gap-6">
                <div className="inline-flex items-center gap-2 rounded-full px-2 py-2 text-[12px] font-semibold text-white">
                  <Sun className="h-[15px] w-[15px] text-[#D9FF57]" strokeWidth={1.9} />
                  Thursday, 23 April
                </div>
                <div className="text-center">
                  <p className="text-[12px] font-medium text-[#F3F8FF]">Good morning,</p>
                  <p className="mt-1 text-[20px] font-semibold leading-none tracking-[-0.05em] text-[#F7F8FC]">{userProfile.name}</p>
                </div>
                <div className="flex items-center gap-3">
                  <OperationalWalletStatus compact />
                  <div className="rounded-full border border-[#D9FF57]/38 bg-[#D9FF57]/20 px-4 py-2 text-[12px] font-semibold text-[#FFFFE5] shadow-[0_16px_32px_rgba(215,255,79,0.12),inset_0_1px_0_rgba(247,248,252,0.16)]">
                    <span className="inline-flex items-center gap-2">
                      <span className="zila-live-dot h-1.5 w-1.5 rounded-full bg-[#D9FF57]" />
                      {syncState.label}
                    </span>
                  </div>
                  <button
                    type="button"
                    className="zila-button-hover inline-flex h-9 w-9 items-center justify-center rounded-full border border-white/36 bg-white/[0.28] text-white shadow-[0_14px_28px_rgba(31,68,116,0.18),inset_0_1px_0_rgba(247,248,252,0.20)]"
                    aria-label="Notifications"
                  >
                    <Bell className="h-[16px] w-[16px]" strokeWidth={1.9} />
                  </button>
                  <Link
                    href="/payments"
                    className="zila-button-hover inline-flex items-center gap-2 rounded-full border border-[#D7E8FF]/20 bg-[#173D6D] px-3.5 py-2 text-[12px] font-semibold text-white shadow-[0_18px_34px_rgba(31,68,116,0.26),inset_0_1px_0_rgba(255,255,255,0.10)]"
                  >
                    Make Payment
                    <ArrowUpRight className="h-3.5 w-3.5" strokeWidth={2} />
                  </Link>
                </div>
                </div>
              </div>
            ) : (
              <div>
                <ContextualBackNav className="mb-4" />
                <div className="flex items-start justify-between gap-6">
                  <div className="max-w-[720px]">
                    <p className="text-[12px] font-semibold uppercase tracking-[0.22em] text-[#7CF3FF]">
                      {meta.eyebrow}
                    </p>
                    <h2 className="mt-2 text-[28px] font-semibold leading-[0.98] tracking-[-0.055em] text-[#F7F8FC]">
                      {meta.title}
                    </h2>
                    <p className="mt-2 text-[13px] leading-[1.6] text-[#A7B0C5]">{meta.summary}</p>
                  </div>
                  <div className="flex flex-col items-end gap-3">
                    <OperationalWalletStatus />
                    <Link
                      href={primaryFlowAction.href}
                      className="group inline-flex items-center gap-3 rounded-full border border-[#D9FF57]/16 bg-[#D9FF57]/[0.08] px-4 py-2 text-[13px] font-semibold text-[#EAFFB4] transition hover:bg-[#D9FF57]/[0.12]"
                    >
                      <span className="flex flex-col leading-none">
                        <span>{primaryFlowAction.label}</span>
                        <span className="mt-1 hidden text-[10px] font-medium text-[#B9C8DF] xl:inline">{primaryFlowAction.description}</span>
                      </span>
                      <ArrowUpRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5" strokeWidth={2} />
                    </Link>
                  </div>
                </div>
              </div>
            )}
          </header>

          <main className={isHome ? "pb-6 pt-2.5" : "pb-6 pt-3"}>{children}</main>
        </div>
      </div>
    </div>
  );
}

export default DesktopShell;
